import { sql } from "drizzle-orm";
import type { BookingLookupRequest } from "@booking/contracts";
import { getDb, type BookingDatabase } from "@booking/database";
import { normalizeEmail, normalizeWhatsApp } from "@booking/validation";
import { DomainError } from "./errors";

const rows = <T>(value: unknown) => value as T[];

export async function getPublicBusiness(slug:string,db:BookingDatabase=getDb()) {
  const result=rows<Record<string,unknown>>(await db.execute(sql`select slug,name,type,email,phone,address,timezone,currency from businesses where slug=${slug} and is_active limit 1`));
  if(!result[0]) throw new DomainError("BUSINESS_NOT_FOUND","Business was not found.",404); return result[0];
}
export async function listAccommodationTypes(db:BookingDatabase=getDb()) { return rows<Record<string,unknown>>(await db.execute(sql`select t.slug,t.name,t.description,t.base_price::int as "basePrice",t.capacity_per_unit as "capacityPerUnit" from accommodation_types t join businesses b on b.id=t.business_id where b.slug='glamping' and b.is_active and t.is_active order by t.sort_order,t.name`)); }
export async function accommodationType(slug:string,db:BookingDatabase=getDb()) { const result=rows<Record<string,unknown>>(await db.execute(sql`select t.slug,t.name,t.description,t.base_price::int as "basePrice",t.capacity_per_unit as "capacityPerUnit" from accommodation_types t join businesses b on b.id=t.business_id where b.slug='glamping' and t.slug=${slug} and b.is_active and t.is_active limit 1`)); if(!result[0]) throw new DomainError("PRODUCT_NOT_FOUND","Accommodation type was not found.",404); return result[0]; }
export async function listJeepPackages(db:BookingDatabase=getDb()) { return rows<Record<string,unknown>>(await db.execute(sql`select p.slug,p.name,p.description,p.price_per_unit::int as "pricePerUnit",p.capacity_per_unit as "capacityPerUnit",coalesce(json_agg(json_build_object('id',s.id,'name',s.name,'departureTime',s.departure_time) order by s.departure_time) filter(where s.id is not null),'[]') as "departureSlots" from jeep_packages p join businesses b on b.id=p.business_id left join jeep_departure_slots s on s.jeep_package_id=p.id and s.is_active where b.slug='jeep' and b.is_active and p.is_active group by p.id order by p.sort_order,p.name`)); }
export async function jeepPackage(slug:string,db:BookingDatabase=getDb()) { const result=(await listJeepPackages(db)).find(p=>p.slug===slug); if(!result) throw new DomainError("PRODUCT_NOT_FOUND","Jeep package was not found.",404); return result; }

export async function lookupBooking(input:BookingLookupRequest,db:BookingDatabase=getDb()) {
  const email=input.email?normalizeEmail(input.email):null, whatsapp=input.whatsapp?normalizeWhatsApp(input.whatsapp):null;
  const result=rows<{bookingId:string;bookingCode:string;status:string;paymentStatus:string;totalAmount:number;requiredDpAmount:number;verifiedPaidAmount:number;remainingAmount:number;expiresAt:Date|null}>(await db.execute(sql`select id as "bookingId",booking_code as "bookingCode",status,payment_status as "paymentStatus",total_amount::int as "totalAmount",required_dp_amount::int as "requiredDpAmount",verified_paid_amount::int as "verifiedPaidAmount",remaining_amount::int as "remainingAmount",expires_at as "expiresAt" from bookings where upper(booking_code)=upper(${input.bookingCode}) and ((${email}::text is not null and customer_email_normalized=${email}) or (${whatsapp}::text is not null and customer_whatsapp_normalized=${whatsapp})) limit 1`));
  if(!result[0]) throw new DomainError("BOOKING_LOOKUP_FAILED","Booking and contact details could not be matched.",404); return result[0];
}
export async function getBookingStatus(code:string,bookingId:string,db:BookingDatabase=getDb()) { const result=rows<Record<string,unknown>>(await db.execute(sql`select b.booking_code as "bookingCode",b.booking_type as "bookingType",b.status,b.payment_status as "paymentStatus",b.customer_name as "customerName",b.quantity,b.guest_count as "guestCount",b.subtotal_amount::int as "subtotalAmount",b.total_amount::int as "totalAmount",b.dp_percentage as "dpPercentage",b.required_dp_amount::int as "requiredDpAmount",b.verified_paid_amount::int as "verifiedPaidAmount",b.remaining_amount::int as "remainingAmount",b.expires_at as "expiresAt",b.requires_review as "requiresReview",b.booking_source as "bookingSource",coalesce(g.product_name_snapshot,j.package_name_snapshot) as "productName",coalesce(g.unit_price_snapshot,j.unit_price_snapshot)::int as "unitPrice",g.night_count as "nightCount",coalesce(g.check_in_date,j.tour_date)::text as "startDate",g.check_out_date::text as "endDate",j.departure_time_snapshot::text as "departureTime",i.status as "invoiceStatus",i.invoice_number as "invoiceNumber",pr.status as "latestProofStatus",pr.rejection_reason as "latestProofRejectionReason",pr.created_at as "latestProofCreatedAt" from bookings b left join glamping_booking_details g on g.booking_id=b.id left join jeep_booking_details j on j.booking_id=b.id left join invoices i on i.booking_id=b.id left join lateral(select status,rejection_reason,created_at from payment_proofs where booking_id=b.id order by created_at desc limit 1)pr on true where b.id=${bookingId}::uuid and b.booking_code=${code} limit 1`)); if(!result[0]) throw new DomainError("BOOKING_NOT_FOUND","Booking was not found.",404); return result[0]; }
