import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Clock3, Compass, ExternalLink, Map, MessageCircle, Mountain, ShieldCheck, Sunrise, Users } from "lucide-react";
import { Footer, Header } from "@/components/site-chrome";
import { JeepLandingSearch } from "@/components/landing-search";
import { LandingMotion } from "@/components/landing-motion";
import { PremiumFaq } from "@/components/premium-faq";
import { getTourStayBookingUrl, jeepBrochurePath, jeepCatalogPackages, tourStayCatalogPackages } from "@/lib/jeep-catalog";
import { rupiah } from "@/lib/api";
import { jeepMedia, jeepPackageImage } from "@/lib/jeep-media";

const experiences = [
  { icon: Sunrise, title: "Berangkat tepat waktu", text: "Slot perjalanan yang jelas untuk membantu Anda merencanakan pagi dengan nyaman." },
  { icon: Compass, title: "Kru berpengalaman", text: "Perjalanan ditemani pengemudi yang memahami karakter medan dan operasional setempat." },
  { icon: ShieldCheck, title: "Armada terjaga", text: "Setiap booking menggunakan unit fisik dan tetap terlindungi dari overbooking." },
];

const tourStayGroups = ["Family Adventure - Deluxe", "Group Adventure - Twin Bed"].map((name) => ({
  name,
  items: tourStayCatalogPackages.filter((item) => item.bundleName === name),
}));

export default function Home() {
  return <><Header/><main className="brand-home jeep-home"><LandingMotion/>
    <section className="brand-hero jeep-hero"><Image className="brand-cover-image" src={jeepMedia.hero} alt="Jeep Shakila di lereng Nepal Van Java" fill priority quality={92} sizes="100vw"/><div className="brand-hero-overlay"/><div className="brand-hero-content"><p className="brand-kicker">WISATA JEEP SHAKILA · NEPAL VAN JAVA</p><h1>Menjelajah lereng<br/><em>lebih dekat.</em></h1><p>Perjalanan Jeep privat dengan persiapan yang rapi, suasana yang personal, dan waktu yang dibuat untuk menikmati setiap lanskap.</p><Link className="brand-button brand-button-light" href="/availability">Rencanakan perjalanan <ArrowRight/></Link></div><div className="brand-scroll-cue"><span>JELAJAHI</span><i/></div></section>
    <div className="brand-booking-shell jeep-booking-shell"><JeepLandingSearch/></div>
    <section className="brand-intro" data-reveal><p className="brand-kicker">CARA SHAKILA MENEMANI</p><h2>Perjalanan yang berani, layanan yang tetap tenang.</h2><p className="brand-lead">Shakila membawa standar keramahtamahan yang sama ke perjalanan Jeep: reservasi yang mudah, operasional yang jelas, dan pengalaman lapangan yang terasa personal.</p></section>
    <section id="routes" className="brand-showcase jeep-catalog" data-reveal><div className="brand-section-heading"><div><p className="brand-kicker">KATALOG RESMI SHAKILA</p><h2>Paket Tour & Stay</h2><p className="jeep-catalog-intro">Delapan pilihan paket lengkap dari brosur resmi: Jeep Tour, penginapan, sarapan, makan, tiket wisata, dan ojek sesuai ketentuan rute.</p></div><div className="jeep-catalog-actions"><a className="jeep-brochure-link" href={jeepBrochurePath} target="_blank" rel="noreferrer">Lihat Price List Lengkap <ExternalLink/></a></div></div><div className="tour-stay-groups">
      {tourStayGroups.map((group)=><section className="tour-stay-group" key={group.name}><header><p>PILIHAN PAKET LENGKAP</p><h3>{group.name}</h3><span>{group.items[0]?.capacity} · {group.items[0]?.composition.join(" · ")}</span></header><div className="tour-stay-grid">{group.items.map((item)=><article className="tour-stay-card" key={item.slug}><div className="tour-stay-card-head"><span>{item.badge}</span><p>{item.routeName}</p><h4>{rupiah(item.priceAmountIdr)}</h4><small>Setara {rupiah(item.displayedPerPersonAmountIdr)}/{item.displayedPerPersonUnit}</small></div><div className="tour-stay-card-content"><strong>Rute / destinasi</strong><ol>{item.stops.map((stop)=><li key={stop}>{stop}</li>)}</ol><strong>Termasuk dalam paket</strong><ul>{item.inclusions.map((value)=><li key={value}><Check/>{value}</li>)}</ul><p className="tour-stay-card-note">Akhir pekan atau hari libur: tambahan Rp50.000 per paket.</p><small className="tour-stay-asterisk">Keterangan tanda * tidak dicantumkan dalam brosur.</small></div><div className="tour-stay-card-actions"><Link href={`/packages/${item.slug}`}>Lihat Detail <ArrowRight/></Link><a href={getTourStayBookingUrl(item)}>Pilih / Booking <MessageCircle/></a></div></article>)}</div></section>)}
    </div><div className="standalone-catalog-heading"><div><p className="brand-kicker">SEWA JEEP WISATA</p><h2>Paket Jeep Tanpa Menginap</h2><p>Enam pilihan rute dari katalog Jeep Shakila. Harga paket belum termasuk tiket masuk destinasi wisata.</p></div><Link href="/availability">Lihat ketersediaan <ArrowRight/></Link></div><div className="jeep-package-grid">
      {jeepCatalogPackages.map((item, index)=><article className="jeep-package-card" key={item.slug}><div className="jeep-package-visual"><Image src={jeepPackageImage(item.slug)} alt={`Perjalanan ${item.name} Shakila Jeep`} fill quality={88} sizes="(max-width: 720px) 100vw, (max-width: 1100px) 50vw, 33vw"/><span>{String(index + 1).padStart(2,"0")}</span></div><div className="jeep-package-body"><p>{item.category}</p><h3>{item.name}</h3><ol>{item.stops.map((stop)=><li key={stop}>{stop}</li>)}</ol><div className="jeep-package-footer"><div><small>Harga paket</small><strong>{rupiah(item.priceAmountIdr)}</strong></div><Link href={`/packages/${item.slug}`}>Lihat paket <ArrowRight/></Link></div></div></article>)}
    </div></section>
    <section id="fleet" className="brand-split brand-split-reverse" data-reveal><div className="brand-split-image jeep-story"><Image className="brand-cover-image" src={jeepMedia.fleet} alt="Jeep di lanskap pegunungan" fill quality={90} sizes="(max-width: 1000px) 100vw, 52vw"/></div><div className="brand-split-copy"><p className="brand-kicker">PERJALANAN YANG LENGKAP</p><h2>Satu perjalanan, dipersiapkan dengan baik.</h2><p>Dari pemilihan slot hingga keberangkatan, setiap tahap dirancang sederhana. Armada dialokasikan saat booking agar kapasitas yang Anda lihat tetap nyata.</p><div className="brand-facts"><div><Clock3/><span><b>Slot terjadwal</b>Waktu keberangkatan jelas</span></div><div><Users/><span><b>12 unit Jeep</b>Pool armada fisik terkonfirmasi</span></div><div><ShieldCheck/><span><b>DP 50%</b>Minimum pembayaran</span></div></div><Link className="brand-text-link" href="/availability">Pilih perjalanan <ArrowRight/></Link></div></section>
    <section className="brand-values">{experiences.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</section>
    <section id="stories" className="brand-quote jeep-quote"><p className="brand-kicker">SHAKILA GROUP</p><blockquote>“Petualangan terbaik tidak harus terasa terburu-buru. Ia dimulai dengan persiapan yang baik dan ruang untuk menikmati perjalanan.”</blockquote></section>
    <section className="brand-route-notes"><div><Map/><span>RUTE TERPILIH</span></div><i/><div><Mountain/><span>NEPAL VAN JAVA</span></div><i/><div><Compass/><span>KRU LOKAL</span></div></section>
    <section id="faq" className="brand-faq" data-reveal><div><p className="brand-kicker">SEBELUM BERANGKAT</p><h2>Informasi penting.</h2><p className="brand-faq-intro">Detail singkat agar perjalanan terasa nyaman sejak reservasi.</p></div><PremiumFaq items={[{question:"Bagaimana memilih jadwal keberangkatan?",answer:"Pilih tanggal perjalanan, paket tour, dan slot keberangkatan yang tersedia pada halaman reservasi."},{question:"Berapa minimum DP?",answer:"DP minimal 50% dari total booking dan harus dibayar maksimal 12 jam setelah booking dibuat."},{question:"Bagaimana kebijakan pembatalan?",answer:"DP yang telah dibayarkan tidak dapat dikembalikan apabila booking dibatalkan."}]}/></section>
    <section className="brand-cta jeep-cta"><Image className="brand-cover-image" src={jeepMedia.trail} alt="Jeep Shakila di jalur alam" fill quality={90} sizes="100vw"/><div><p className="brand-kicker">PERJALANAN ANDA MENANTI</p><h2>Temukan Nepal van Java lebih dekat.</h2></div><Link className="brand-button brand-button-light" href="/availability">Pesan sekarang <ArrowRight/></Link></section>
  </main><Footer/></>;
}
